CREATE TABLE acs (
    id VARCHAR(2) PRIMARY KEY,
    "name" TEXT NOT NULL
);

ALTER TABLE acs
    ADD CONSTRAINT ck_name_len CHECK (char_length("name") <= 100);

CREATE TABLE acs_areas (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    acs_id VARCHAR(2) NOT NULL REFERENCES acs(id)
        ON DELETE CASCADE,
    area_id VARCHAR(4) NOT NULL,
    "name" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    UNIQUE (acs_id, area_id),
    UNIQUE (acs_id, "order")
);

ALTER TABLE acs_areas
    ADD CONSTRAINT ck_name_len CHECK (char_length("name") <= 100);

---- create above / drop below ----

DROP TABLE acs_areas;
DROP TABLE acs;
