CREATE TYPE acs_element_type AS ENUM
    -- "Knowledge", "Risk Management", and "Skill"
    ('K', 'R', 'S');

CREATE TABLE acs_elements (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_id INTEGER NOT NULL REFERENCES acs_area_tasks(id)
        ON DELETE CASCADE,
    "type" acs_element_type NOT NULL,
    public_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    UNIQUE (task_id, "type", public_id)
);

ALTER TABLE acs_elements
    ADD CONSTRAINT ck_content_len CHECK (char_length("content") <= 500);

---- create above / drop below ----

DROP TABLE acs_elements;
DROP TYPE acs_element_type;
