CREATE TABLE element_confidence (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    element_id INTEGER UNIQUE NOT NULL REFERENCES acs_elements(id)
        ON DELETE CASCADE,
    vote SMALLINT NOT NULL
);

---- create above / drop below ----

DROP TABLE element_confidence;
