CREATE TABLE task_references (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_id INTEGER NOT NULL REFERENCES acs_area_tasks (id)
        ON DELETE CASCADE,
    document TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    UNIQUE (task_id, "order")
);

ALTER TABLE task_references
    ADD CONSTRAINT ck_document_len CHECK (char_length(document) <= 100);

---- create above / drop below ----

DROP TABLE task_references;
